Repo maintenance: Switch to PNPM, update and clean dependencies, speed up production tests INTER-553
makma/use-cases-credential-stuffing pull request #123
Opened 2024-02-23 15:11 UTC by JuroUhlar

Dependencies
* switched to PNPM
* Updated everything to `@latest`, fixed resulting errors
* Fixed devDependencies accidentally declared as runtime dependencies

Config files
* Now using common dx-team config files for tsconfig, eslint, and prettier
* For prettier I override `semi` and `trailingComma` for better code/diff readability. We can discuss and remove the overrides if you feel strongly about the default options.

Tests
* I have removed instances of `waitUntil: 'networkidle'`. Turns out it's not really necessary and it caused problems when the tests were running against production, which has a analytics tools making network requests unrelated to use case functionality.
* I am skipping `scraping/protected.ts` test of Firefox as our bot detection does not seem to work properly for Firefox in GitHub CI. I will [communicate the issue](https://fingerprintjs.slack.com/archives/C0451H4KC0G/p1709559853768359) to the Platform team and remove the skip once the issue is resolved.
* Playwright reports now include UI screenshots of failed tests for easier debugging

2024-03-04 18:01 UTC, ilfa requested changes
Need to fix badges markup 
![image](https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/assets/1009415/23ccd36f-9ceb-42a3-9391-ba1bd1c066b2)

2024-03-04 18:58 UTC, JuroUhlar commented
> 270bbbf

Shold be fixed, thanks! https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/pull/123/commits/270bbbf540f81040a853aa6d6702cdd0d20ac505

2024-03-04 18:59 UTC, JuroUhlar commented
> Need to fix badges markup ![image](https://private-user-images.githubusercontent.com/1009415/309854685-23ccd36f-9ceb-42a3-9391-ba1bd1c066b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzkwNTYsIm5iZiI6MTcwOTU3ODc1NiwicGF0aCI6Ii8xMDA5NDE1LzMwOTg1NDY4NS0yM2NjZDM2Zi05Y2ViLTQyYTMtOTM5MS1iYTFiZDFjMDY2YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTg1OTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNhZTEwMmI5YmVjOGFlNGM1YzhiNzY3ZTg3Mjc1Yzc4MGJkZmQyYjA3MDBmZTBkNDJmNTA0NzYyZDI0YmRlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B57lDj5yM1Y7WuCqD4s4eBwJkV8Gw217K0g_wawSbNU)

@ilfa should be fixed. thanks!

https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/pull/123/commits/270bbbf540f81040a853aa6d6702cdd0d20ac505

2024-03-05 16:10 UTC, ilfa submitted a review, later dismissed

2024-03-05 18:16 UTC, ilfa approved these changes

2024-03-05 18:17 UTC, merged